# Generated by Django 4.0.2 on 2023-12-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavern_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
