# Generated by Django 4.0.2 on 2023-12-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tavern_app', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł sesji')),
                ('date', models.DateField(verbose_name='Data sesji')),
                ('time', models.TimeField(verbose_name='Godzina sesji')),
                ('number_of_players', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], verbose_name='Liczba poszukiwanych graczy')),
                ('description', models.TextField(verbose_name='Opis sesji')),
                ('difficulty', models.IntegerField(choices=[('Pokojowa', 'Pokojowa'), ('Zrównoważona', 'Zrównoważona'), ('Niebezpieczna', 'Niebezpieczna'), ('Śmiertelnie groźna', 'Śmiertelnie groźna')], verbose_name='Poziom trudności przygody')),
                ('adult_only', models.BooleanField(verbose_name='Sesja tylko dla dorosłych')),
                ('other_requirements', models.TextField(verbose_name='Inne wymagania')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
