# Generated by Django 4.0.2 on 2023-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern_app', '0008_alter_mastersession_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersession',
            name='adult_only',
            field=models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], max_length=50, verbose_name='Sesja tylko dla dorosłych'),
        ),
    ]
