# Generated by Django 4.0.2 on 2023-12-07 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tavern_app', '0009_alter_mastersession_adult_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł sesji')),
                ('date', models.DateField(verbose_name='Data sesji')),
                ('time', models.TimeField(verbose_name='Godzina sesji')),
                ('description', models.TextField(verbose_name='Opis sesji')),
                ('difficulty', models.CharField(choices=[('Pokojowa', 'Pokojowa'), ('Zrównoważona', 'Zrównoważona'), ('Niebezpieczna', 'Niebezpieczna'), ('Śmiertelnie groźna', 'Śmiertelnie groźna')], max_length=50, verbose_name='Oczekiwany poziom trudności przygody')),
                ('adult_only', models.CharField(choices=[('TAK', 'TAK'), ('NIE', 'NIE')], max_length=50, verbose_name='Sesja tylko dla dorosłych')),
                ('other_requirements', models.TextField(verbose_name='Inne wymagania')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
