# Generated by Django 4.0.2 on 2023-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavern_app', '0014_mastersession_counter_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamersession',
            name='is_master_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
